name: Build APK

on:
  push:
    branches:
      - '*'
    
jobs:
  check:
    name: Check whether to build or not
    runs-on: ubuntu-latest
    outputs:
      buildapk: ${{steps.step2.outputs.buildapk}}
    steps:
      - id: step1
        uses: actions/checkout@v3
      - id: step2
        run: echo "buildapk=$(cat buildapk.txt)" >> $GITHUB_OUTPUT
  test:
    name: Test output
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{needs.check.outputs.buildapk}}
          echo $(git rev-parse "$GITHUB_SHA")
          echo ${{ github.event.head_commit.message }}
          echo $(git rev-parse $GITHUB_SHA | cut -c 1-8).apk
  build:
    name: Building Debug APK
    needs: check
    if: needs.check.outputs.buildapk == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Firebase login
        run: |
          curl -X POST -H "Content-Type: application/json" -H "X-Access-Token: ${{ secrets.APITOKEN }}" -d "{\"commit_hash\" : \"$(git rev-parse "$GITHUB_SHA")\", \"commit_msg\" : \"${{ github.event.head_commit.message }}\", \"date\" : \"$(date '+%d-%m-%Y')\", \"filename\" : \"$(git rev-parse $GITHUB_SHA | cut -c 1-8).apk\"}" ${{ secrets.NGROK_URL }}/newindex
          dart pub global activate flutterfire_cli
          curl -sL https://firebase.tools | bash
          flutterfire configure -p ${{ secrets.PROJ_ID }} --platforms="android,ios" -i com.example.navigation \
          -a com.example.navigation -m -a com.example.navigation --token=${{ secrets.FIREBASE_TOKEN }}
        shell: bash
      - name: Extract SDK and load Access keys
        run: |
          curl -o heresdk-explore-flutter.tar.gz https://dl.dropboxusercontent.com/s/2rgack3gpf0j5kp/heresdk-explore-flutter-4.13.0.0.3315.tar.gz?dl=0
          echo "${{ secrets.HereCreds }}" > credentials.env
          mkdir -p plugins/here_sdk
          tar xzf heresdk-explore-flutter.tar.gz -C plugins/here_sdk
          echo "FILENAME=$(git rev-parse $GITHUB_SHA | cut -c 1-8).apk" >> $GITHUB_ENV
        shell: bash
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --debug
          cp build/app/outputs/flutter-apk/app-debug.apk ./$FILENAME
          curl -X POST -H "Content-Type: multipart/form-data" -H "X-Access-Token: ${{ secrets.APITOKEN }}" -F apk=@$FILENAME ${{ secrets.NGROK_URL }}/newbuild
