name: Build APK

on:
  push:
    branches:
      - '*'
    
jobs:
  build:
    name: Building Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Firebase login
        run: |
          dart pub global activate flutterfire_cli
          curl -sL https://firebase.tools | bash
          flutterfire configure -p ${{ secrets.PROJ_ID }} --platforms="android,ios" -i com.example.navigation \
          -a com.example.navigation -m -a com.example.navigation --token=${{ secrets.FIREBASE_TOKEN }}
        shell: bash
      - name: Extract SDK and prepare for building
        run: |
          curl -o heresdk-explore-flutter.tar.gz https://dl.dropboxusercontent.com/s/2rgack3gpf0j5kp/heresdk-explore-flutter-4.13.0.0.3315.tar.gz?dl=0
          echo "${{ secrets.HereCreds }}" > credentials.env
          mkdir -p plugins/here_sdk
          tar xzf heresdk-explore-flutter.tar.gz -C plugins/here_sdk
          echo "FILENAME=$(git rev-parse $GITHUB_SHA | cut -c 1-8).apk" >> $GITHUB_ENV
          echo "RELEASE_NOTES=$(cat release-notes.txt)" >> $GITHUB_ENV
        shell: bash
      - name: Update index on Release server
        run : |
          curl -X POST -H "Content-Type: application/json" -H "X-Access-Token: ${{ secrets.APITOKEN }}" -d "{\"commit_hash\" : \"$(git rev-parse "$GITHUB_SHA")\", \"commit_msg\" : \"${{ github.event.head_commit.message }}\", \"date\" : \"$(date '+%d-%m-%Y')\", \"filename\" : \"$FILENAME\", \"release_notes\" : \"$RELEASE_NOTES\"}" ${{ secrets.NGROK_URL }}/newindex
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --debug
          cp build/app/outputs/flutter-apk/app-debug.apk ./$FILENAME
      - name: Uploading build APK to release server
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" -H "X-Access-Token: ${{ secrets.APITOKEN }}" -F apk=@$FILENAME ${{ secrets.NGROK_URL }}/newbuild
