name: Build APK

on:
  push:
    branches:
      - '*'
    
jobs:
  check:
    name: Check whether to build or not
    runs-on: ubuntu-latest
    outputs:
      buildapk: ${{steps.step2.outputs.buildapk}}
    steps:
      - id: step1
        uses: actions/checkout@v3
      - id: step2
        run: echo "buildapk=$(cat buildapk.txt)" >> $GITHUB_OUTPUT
  test:
    name: Test output
    needs: check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.check.outputs.buildapk}}
  build:
    name: Building Debug APK
    needs: check
    if: needs.check.outputs.buildapk == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - name: Firebase login
        run: |
          dart pub global activate flutterfire_cli
          curl -sL https://firebase.tools | bash
          flutterfire configure -p ${{ secrets.PROJ_ID }} --platforms="android,ios" -i com.example.navigation \
          -a com.example.navigation -m -a com.example.navigation --token=${{ secrets.FIREBASE_TOKEN }}
        shell: bash
      - name: Extract SDK and load Access keys
        run: |
          curl -o heresdk-explore-flutter.tar.gz https://dl.dropboxusercontent.com/s/2rgack3gpf0j5kp/heresdk-explore-flutter-4.13.0.0.3315.tar.gz?dl=0
          echo "${{ secrets.HereCreds }}" > credentials.env
          mkdir -p plugins/here_sdk
          tar xzf heresdk-explore-flutter.tar.gz -C plugins/here_sdk
        shell: bash
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: Navigation Release APK
          path: build/app/outputs/flutter-apk/app-release.apk