name: Build APK

on:
  push:
    branches:
      - '*'
    
jobs:
  container-build-and-push:
    runs-on: ubuntu-latest
    container:
      image: am271/flutter-apk-builder:heresdk
      env:
        NGROK_URL: ${{ secrets.URL }}
        APITOKEN: ${{ secrets.APITOKEN }}
      options: --cpus 2
    steps:
      - name: Extract Here Maps SDK
        run: |
          sudo chown $UID:$GID -R $(pwd)
          mkdir -p plugins/here_sdk
          tar xzf /home/developer/heresdk-explore-flutter.tar.gz -C plugins/here_sdk
        shell: bash
      - name: Build Debug APK
        run: |
          echo "${{ secrets.CREDS }}" > credentials.env
          echo "${{ secrets.FIREBASE_CREDS }}" > lib/firebase_options.dart
          flutter pub get
          flutter build apk --debug
        shell: bash
      - name: Upload APK
        run: bash newbuild.sh
